spring:
  datasource:
    url: jdbc:mysql://db:3306/petcare?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: pet
    password: pet
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui/index.html

jwt:
  secret: Chave26@21Segura354!$%Para984%&JWT@
