spring:
  datasource:
    url: jdbc:mysql://db:3306/petcare?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: pet
    password: pet
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui/index.html

jwt:
  secret: ${JWT_SECRET}

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8082

jwt:
  secret: TesteJWT123456!@#


